shared:
    image: node:8

jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - install: npm install
            - test: npm test
    publish:
        requires: main
        steps:
            - install: npm install --no-save semantic-release@^7
            - publish: npm run semantic-release
        secrets:
            # Publishing to NPM
            - NPM_TOKEN
            # Github token to push tags to Git
            - GH_TOKEN
